version: 2

models:
  - name: dim_vendors
    description: Taxi technology vendor dimension table
    columns:
      - name: vendor_id
        description: Unique vendor identifier
      - name: vendor_name
        description: Company name of the vendor